---
title: ""
output: 
  html_document:
    theme: cerulean
    toc: false
    toc_float: false
    number_sections: false
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(sf)
library(leaflet)

psrc.logo <- here('data','psrc-logo.png')
trends.logo <- here('data','puget-sound-trends.png')
wgs84 <- 4326
spn <- 2285 

psrc.zipcodes <- st_read(here('data', 'psrc_zipcodes.shp')) %>% st_transform(wgs84) %>% select(zipcode)
psrc.zipcodes.centroids <- psrc.zipcodes %>% st_transform(spn) %>% st_centroid() %>% st_transform(wgs84)

zipcode.data <- read_csv(here('data', 'staff-zipcodes.csv')) %>% mutate(response=1, Zip=as.character(Zip)) 
zipcode.point.response <- left_join(psrc.zipcodes.centroids, zipcode.data, by=c("zipcode"="Zip")) %>% drop_na()

i <- awesomeIcons(icon = 'user',iconColor = 'black',library = 'fa')

m <- leaflet() %>% 
        addProviderTiles(providers$CartoDB.Positron) %>%
        
        addLayersControl(baseGroups = c("Base Map"),
                         overlayGroups = c("Zipcode","Responses"),
                         options = layersControlOptions(collapsed = TRUE)) %>%
        
        addEasyButton(easyButton(
            icon="fa-globe", title="Region",
            onClick=JS("function(btn, map){map.setView([47.615,-122.257],8.5); }"))) %>%
        
        addPolygons(data=psrc.zipcodes,
                    fillOpacity = 0.0,
                    opacity = 1.0,
                    weight = 1,
                    color = "#91268F",
                    dashArray = "1",
                    group = "Zipcode") %>%
        
        addAwesomeMarkers(data=zipcode.point.response, 
                          icon = i, 
                          clusterOptions = markerClusterOptions(),
                          group="Responses")

```

```{r, echo=FALSE}
m
```
